spring:
  output:
    ansi:
      enabled: always
  batch:
    job:
      names: ${job.name:helloWorldJob,withParamJob}
    jdbc:
      initialize-schema: ALWAYS
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/spring_batch_exam?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    driver-class-name:
    username: root
    password:
  jpa:
    show-sql: true